# Generated by Django 4.2 on 2023-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="online",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
