# Generated by Django 4.2 on 2023-05-02 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_group_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="user",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
