# Generated by Django 4.2 on 2023-05-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_user_online"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="online",
            new_name="is_online",
        ),
    ]
