# Generated by Django 4.2 on 2023-05-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_user_online"),
        ("chat", "0003_alter_group_user"),
    ]

    operations = []
