# Generated by Django 4.2 on 2023-05-05 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_merge_0002_user_online_0003_alter_group_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="online",
            new_name="is_online",
        ),
    ]
